"""GENERATED by agent/codegen.compile_spec. Do not edit by hand.

Compiled from 8 agent proposed rules and 4 invariants into a
Hypothesis RuleBasedStateMachine (design section 7.3). Drives the PayFlow HTTP
API only. Regenerate with `uv run agent-run`; this file is the committed current
accepted Layer 1 spec.

  SUT base URL: env PAYFLOW_SUT_BASE_URL
  Capture fee:  env PAYFLOW_CAPTURE_FEE (harness supplied, not from OpenAPI)
"""

from __future__ import annotations

import os
import uuid

import httpx
from hypothesis import settings
from hypothesis.stateful import Bundle, RuleBasedStateMachine, invariant, rule
from hypothesis.strategies import integers

BASE_URL = os.environ.get("PAYFLOW_SUT_BASE_URL", "http://127.0.0.1:8000")
CAPTURE_FEE = int(os.environ.get("PAYFLOW_CAPTURE_FEE", "30"))

MIN_AMOUNT = max(CAPTURE_FEE * 4, 400)
MAX_AMOUNT = 100_000


def _key() -> dict:
    return {"Idempotency-Key": uuid.uuid4().hex}


class PayFlowGeneratedMachine(RuleBasedStateMachine):
    accounts = Bundle("accounts")
    intents = Bundle("intents")

    def __init__(self) -> None:
        super().__init__()
        # Per-step checks read only entities this instance created (self._model,
        # self._merchants). For the once-per-example conservation check (INV-4) we
        # record a baseline of the shared system accounts here and assert MY net
        # delta against it in teardown: examples run sequentially, so between this
        # baseline and teardown only this instance's operations move those accounts,
        # which makes a true global debit==credit check safe on a shared server.
        self._client = httpx.Client(base_url=BASE_URL, timeout=30.0)
        self._model: dict[str, dict] = {}
        self._merchants: list[str] = []
        self._merchant_expected: dict[str, int] = {}
        self._system_accounts = ("acct_external_settlement", "acct_holds", "acct_platform_fees")
        self._system_baseline = {a: self._balance(a) for a in self._system_accounts}

    # teardown() is composed by the compiler (render_module): it runs the
    # once-per-example invariant checks (conservation, non-negativity), then
    # always closes the client.

    # -- shared helpers ---------------------------------------------------

    def _remote_intent(self, intent_id: str) -> dict:
        response = self._client.get(f"/payment_intents/{intent_id}")
        assert response.status_code == 200, response.text
        return response.json()

    def _balance(self, account_id: str) -> int:
        response = self._client.get(f"/accounts/{account_id}/balance")
        assert response.status_code == 200, response.text
        return response.json()["balance"]

    def _assert_unchanged(self, intent_id: str, tag: str) -> None:
        model = self._model[intent_id]
        body = self._remote_intent(intent_id)
        assert body["state"] == model["state"], f"{tag} state changed on a rejected call"
        assert body["captured_amount"] == model["captured"], f"{tag} captured changed on a rejected call"
        assert body["refunded_amount"] == model["refunded"], f"{tag} refunded changed on a rejected call"

    @rule(intent=intents)
    def authorize(self, intent):
        # [RULE authorize] effect=authorize legal_states=['CREATED']
        model = self._model[intent]
        if model["state"] not in {'CREATED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/authorize", headers=_key())
        assert response.status_code == 200, f"[RULE authorize] expected 200 in state {model['state']}, got {response.status_code}: {response.text}"
        model["authorized"] = model["amount"]
        model["state"] = "AUTHORIZED"

    @rule(intent=intents)
    def authorize_illegal_state_rejected(self, intent):
        # [RULE authorize_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {'CREATED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/authorize", headers=_key())
        assert response.status_code == 409, f"[RULE authorize_illegal_state] expected 409 in state {model['state']}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE authorize_illegal_state]")

    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def capture(self, intent, raw):
        # [RULE capture] effect=capture legal_states=['AUTHORIZED', 'PARTIALLY_CAPTURED']
        model = self._model[intent]
        if model["state"] not in {'AUTHORIZED', 'PARTIALLY_CAPTURED'}:
            return
        remaining = model["authorized"] - model["captured"]
        if remaining <= CAPTURE_FEE + 1:
            return
        amount = CAPTURE_FEE + 1 + (raw % (remaining - CAPTURE_FEE))
        response = self._client.post(f"/payment_intents/{intent}/capture", json={"amount": amount}, headers=_key())
        assert response.status_code == 200, f"[RULE capture] expected 200 in state {model['state']}, got {response.status_code}: {response.text}"
        model["captured"] += amount
        # The fee is drawn from external settlement, not the merchant (ADR-0005),
        # so the merchant is credited the full captured amount.
        self._merchant_expected[model["merchant"]] += amount
        model["state"] = "CAPTURED" if model["captured"] == model["authorized"] else "PARTIALLY_CAPTURED"

    @rule(intent=intents)
    def capture_over_limit_rejected(self, intent):
        # [RULE capture_over_limit] INV-1 boundary: capture beyond the remaining hold must be rejected
        model = self._model[intent]
        if model["state"] not in {'AUTHORIZED', 'PARTIALLY_CAPTURED'}:
            return
        remaining = model["authorized"] - model["captured"]
        amount = remaining + 1
        response = self._client.post(f"/payment_intents/{intent}/capture", json={"amount": amount}, headers=_key())
        assert response.status_code == 422, f"[RULE capture_over_limit] expected 422 capturing {amount} over remaining {remaining}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE capture_over_limit]")

    @rule(intent=intents)
    def capture_illegal_state_rejected(self, intent):
        # [RULE capture_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {'AUTHORIZED', 'PARTIALLY_CAPTURED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/capture", json={"amount": CAPTURE_FEE + 1}, headers=_key())
        assert response.status_code == 409, f"[RULE capture_illegal_state] expected 409 in state {model['state']}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE capture_illegal_state]")

    @rule(target=accounts)
    def create_account(self):
        # [RULE create_account] operation createAccount
        response = self._client.post("/accounts", json={"name": "acme"}, headers=_key())
        assert response.status_code == 201, f"[RULE create_account] expected 201, got {response.status_code}: {response.text}"
        account_id = response.json()["id"]
        self._merchants.append(account_id)
        self._merchant_expected[account_id] = 0
        return account_id

    @rule(target=intents, account=accounts, amount=integers(min_value=MIN_AMOUNT, max_value=MAX_AMOUNT))
    def create_payment_intent(self, account, amount):
        # [RULE create_payment_intent] operation createPaymentIntent
        response = self._client.post("/payment_intents", json={"merchant_account_id": account, "amount": amount}, headers=_key())
        assert response.status_code == 201, f"[RULE create_payment_intent] expected 201, got {response.status_code}: {response.text}"
        intent_id = response.json()["id"]
        self._model[intent_id] = {"merchant": account, "amount": amount, "authorized": 0, "captured": 0, "refunded": 0, "state": "CREATED"}
        return intent_id

    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def refund_payment_intent(self, intent, raw):
        # [RULE refund_payment_intent] effect=refund legal_states=['CAPTURED', 'PARTIALLY_REFUNDED']
        model = self._model[intent]
        if model["state"] not in {'CAPTURED', 'PARTIALLY_REFUNDED'}:
            return
        refundable = model["captured"] - model["refunded"]
        if refundable < 1:
            return
        amount = 1 + (raw % refundable)
        response = self._client.post(f"/payment_intents/{intent}/refund", json={"amount": amount}, headers=_key())
        assert response.status_code == 200, f"[RULE refund_payment_intent] expected 200 in state {model['state']}, got {response.status_code}: {response.text}"
        model["refunded"] += amount
        self._merchant_expected[model["merchant"]] -= amount
        model["state"] = "REFUNDED" if model["refunded"] == model["captured"] else "PARTIALLY_REFUNDED"

    @rule(intent=intents)
    def refund_payment_intent_over_limit_rejected(self, intent):
        # [RULE refund_payment_intent_over_limit] INV-2 boundary: refund beyond the refundable amount must be rejected
        model = self._model[intent]
        if model["state"] not in {'CAPTURED', 'PARTIALLY_REFUNDED'}:
            return
        refundable = model["captured"] - model["refunded"]
        amount = refundable + 1
        response = self._client.post(f"/payment_intents/{intent}/refund", json={"amount": amount}, headers=_key())
        assert response.status_code == 422, f"[RULE refund_payment_intent_over_limit] expected 422 refunding {amount} over refundable {refundable}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE refund_payment_intent_over_limit]")

    @rule(intent=intents)
    def refund_payment_intent_illegal_state_rejected(self, intent):
        # [RULE refund_payment_intent_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {'CAPTURED', 'PARTIALLY_REFUNDED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/refund", json={"amount": 1}, headers=_key())
        assert response.status_code == 409, f"[RULE refund_payment_intent_illegal_state] expected 409 in state {model['state']}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE refund_payment_intent_illegal_state]")

    @rule(intent=intents)
    def void_payment_intent(self, intent):
        # [RULE void_payment_intent] effect=void legal_states=['CREATED', 'AUTHORIZED', 'PARTIALLY_CAPTURED']
        model = self._model[intent]
        if model["state"] not in {'CREATED', 'AUTHORIZED', 'PARTIALLY_CAPTURED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/void", headers=_key())
        assert response.status_code == 200, f"[RULE void_payment_intent] expected 200 in state {model['state']}, got {response.status_code}: {response.text}"
        model["state"] = "VOIDED"

    @rule(intent=intents)
    def void_payment_intent_illegal_state_rejected(self, intent):
        # [RULE void_payment_intent_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {'CREATED', 'AUTHORIZED', 'PARTIALLY_CAPTURED'}:
            return
        response = self._client.post(f"/payment_intents/{intent}/void", headers=_key())
        assert response.status_code == 409, f"[RULE void_payment_intent_illegal_state] expected 409 in state {model['state']}, got {response.status_code}: {response.text}"
        self._assert_unchanged(intent, "[RULE void_payment_intent_illegal_state]")

    @invariant()
    def captured_le_authorized_always(self):
        # [INV-1] captured_amount <= authorized_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["captured_amount"] <= body["authorized_amount"], f"[INV-1] {intent_id}: captured {body['captured_amount']} > authorized {body['authorized_amount']}"

    @invariant()
    def refunded_le_captured_always(self):
        # [INV-2] refunded_amount <= captured_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["refunded_amount"] <= body["captured_amount"], f"[INV-2] {intent_id}: refunded {body['refunded_amount']} > captured {body['captured_amount']}"

    def _check_global_money_conserved(self):
        # [INV-4] global conservation of money: every ledger movement is a
        # balanced debit/credit pair, so the net change across ALL accounts this
        # instance touched must be exactly zero. Measured as a delta against the
        # per-instance system-account baseline plus this instance's merchant
        # balances (merchants start at zero, so their absolute balance is their
        # delta). A dropped or misweighted pair leaves the net non-zero.
        net = 0
        for account_id, baseline in self._system_baseline.items():
            net += self._balance(account_id) - baseline
        for account_id in self._merchants:
            net += self._balance(account_id)
        assert net == 0, f"[INV-4] money not conserved: net delta across every account this run touched is {net}, must be 0 (debits == credits)"

    def _check_no_negative_internal_balances(self):
        # [INV-3] no merchant, holds, or platform_fees balance ever goes negative;
        # external_settlement is the funding source and may. Merchant checks
        # are scoped to this instance's accounts; holds and platform_fees are
        # globally non-negative by construction (holds only carries outstanding
        # authorizations, platform_fees is only ever credited), so their absolute
        # balance is safe to assert on the shared server.
        for account_id in self._merchants:
            balance = self._balance(account_id)
            assert balance >= 0, f"[INV-3] merchant {account_id} balance is negative: {balance}"
        for account_id in ("acct_holds", "acct_platform_fees"):
            balance = self._balance(account_id)
            assert balance >= 0, f"[INV-3] system account {account_id} balance is negative: {balance}"

    def teardown(self) -> None:
        # Run the once-per-example invariant checks (INV-4 conservation,
        # INV-3 non-negativity), then always close the client. A failure
        # here fails the example and shrinks like any other assertion.
        try:
            self._check_global_money_conserved()
            self._check_no_negative_internal_balances()
        finally:
            self._client.close()


# Budgets are env overridable so a bug hunt can widen the search (examples cost
# time, not tokens) while the committed replay slice stays modest.
_MAX_EXAMPLES = int(os.environ.get('PAYFLOW_SPEC_MAX_EXAMPLES', '50'))
_STEP_COUNT = int(os.environ.get('PAYFLOW_SPEC_STEP_COUNT', '18'))
PayFlowGeneratedMachine.TestCase.settings = settings(
    max_examples=_MAX_EXAMPLES, stateful_step_count=_STEP_COUNT, deadline=None
)
TestGeneratedMachine = PayFlowGeneratedMachine.TestCase
