"""GENERATED by agent/codegen.render_mr. Do not edit by hand.

Compiled from 6 agent proposed metamorphic relations (design section 8.4). Each
test runs a scenario twice against the live PayFlow HTTP API under a transform and
asserts the expected cross run relation. Regenerate with `uv run agent-run`; this
file is the committed current accepted Layer 1 relation suite.

  SUT base URL: env PAYFLOW_SUT_BASE_URL
  Capture fee:  env PAYFLOW_CAPTURE_FEE (harness supplied, not from OpenAPI)
  Examples:     env PAYFLOW_MR_MAX_EXAMPLES (default 20)
"""

from __future__ import annotations

import os
import uuid

import httpx
from hypothesis import given, settings
from hypothesis import strategies as st

BASE_URL = os.environ.get("PAYFLOW_SUT_BASE_URL", "http://127.0.0.1:8000")
CAPTURE_FEE = int(os.environ.get("PAYFLOW_CAPTURE_FEE", "30"))
PLATFORM_FEES = "acct_platform_fees"

MIN_CAPTURE = CAPTURE_FEE + 1
MAX_CAPTURE = 100_000
_MR_MAX_EXAMPLES = int(os.environ.get("PAYFLOW_MR_MAX_EXAMPLES", "20"))


def _client() -> httpx.Client:
    return httpx.Client(base_url=BASE_URL, timeout=30.0)


def _key() -> dict:
    return {"Idempotency-Key": uuid.uuid4().hex}


def _fixed_key(value: str) -> dict:
    return {"Idempotency-Key": value}


def _new_merchant(c, tag):
    r = c.post("/accounts", json={"name": "mr"}, headers=_key())
    assert r.status_code == 201, f"{tag} create account expected 201, got {r.status_code}: {r.text}"
    return r.json()["id"]


def _new_intent(c, merchant, amount, tag):
    r = c.post("/payment_intents", json={"merchant_account_id": merchant, "amount": amount}, headers=_key())
    assert r.status_code == 201, f"{tag} create intent expected 201, got {r.status_code}: {r.text}"
    return r.json()["id"]


def _authorize(c, intent, tag):
    r = c.post(f"/payment_intents/{intent}/authorize", headers=_key())
    assert r.status_code == 200, f"{tag} authorize expected 200, got {r.status_code}: {r.text}"


def _capture(c, intent, amount, tag, key=None):
    headers = _fixed_key(key) if key else _key()
    r = c.post(f"/payment_intents/{intent}/capture", json={"amount": amount}, headers=headers)
    assert r.status_code == 200, f"{tag} capture of {amount} expected 200, got {r.status_code}: {r.text}"
    return r.json()


def _void(c, intent, tag):
    r = c.post(f"/payment_intents/{intent}/void", headers=_key())
    assert r.status_code == 200, f"{tag} void expected 200, got {r.status_code}: {r.text}"


def _refund(c, intent, amount, tag):
    r = c.post(f"/payment_intents/{intent}/refund", json={"amount": amount}, headers=_key())
    assert r.status_code == 200, f"{tag} refund of {amount} expected 200, got {r.status_code}: {r.text}"
    return r.json()


def _get_intent(c, intent, tag):
    r = c.get(f"/payment_intents/{intent}")
    assert r.status_code == 200, f"{tag} get intent expected 200, got {r.status_code}: {r.text}"
    return r.json()


def _balance(c, account, tag):
    r = c.get(f"/accounts/{account}/balance")
    assert r.status_code == 200, f"{tag} balance expected 200, got {r.status_code}: {r.text}"
    return r.json()["balance"]


def _check_split_capture(part1, part2, fee_adjusted, tag):
    total = part1 + part2
    with _client() as c:
        pf0 = _balance(c, PLATFORM_FEES, tag)
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, total, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, total, tag)
        base_merchant = _balance(c, mb, tag)
        base_fee_delta = _balance(c, PLATFORM_FEES, tag) - pf0

        pf1 = _balance(c, PLATFORM_FEES, tag)
        mv = _new_merchant(c, tag)
        iv = _new_intent(c, mv, total, tag)
        _authorize(c, iv, tag)
        _capture(c, iv, part1, tag)
        _capture(c, iv, part2, tag)
        var_merchant = _balance(c, mv, tag)
        var_fee_delta = _balance(c, PLATFORM_FEES, tag) - pf1

    # The fee is drawn from external settlement, not the merchant (ADR-0005), so
    # the merchant keeps the full captured amount however the capture is split: the
    # merchant balance is always exactly equivalent. The fee deviation lives on
    # platform_fees, which gains exactly one flat fee per capture, so splitting one
    # capture into two adds exactly one fee (the fee_adjusted relation).
    exp_fee_delta = base_fee_delta + CAPTURE_FEE if fee_adjusted else base_fee_delta
    assert var_merchant == base_merchant, (
        f"{tag} split capture: variant merchant balance {var_merchant} != baseline "
        f"{base_merchant}; the merchant keeps the full captured amount, so splitting a "
        f"capture must leave the merchant unchanged"
    )
    assert var_fee_delta == exp_fee_delta, (
        f"{tag} split capture: platform_fees gained {var_fee_delta} across two captures "
        f"but expected {exp_fee_delta} (one capture gained {base_fee_delta}, "
        f"fee_adjusted={fee_adjusted}); every capture must contribute exactly one flat "
        f"fee to platform_fees, so splitting one capture into two adds exactly one fee"
    )


def _check_scale_amounts(base_amount, k, fee_adjusted, tag):
    scaled = base_amount * k
    with _client() as c:
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, base_amount, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, base_amount, tag)
        base_merchant = _balance(c, mb, tag)

        mv = _new_merchant(c, tag)
        iv = _new_intent(c, mv, scaled, tag)
        _authorize(c, iv, tag)
        _capture(c, iv, scaled, tag)
        var_merchant = _balance(c, mv, tag)

    capture_count = 1
    if fee_adjusted:
        deviation = (k - 1) * CAPTURE_FEE * capture_count
        expected = k * base_merchant + deviation
    else:
        expected = k * base_merchant
    assert var_merchant == expected, (
        f"{tag} scale by {k}: variant merchant balance {var_merchant} != expected "
        f"{expected} (baseline {base_merchant}, fee {CAPTURE_FEE}, "
        f"fee_adjusted={fee_adjusted}); scaling every amount by k scales balances by k "
        f"except the flat fee, whose deviation is exactly (k-1)*fee*capture_count"
    )


def _check_split_refund(part1, part2, fee_adjusted, tag):
    total = part1 + part2
    with _client() as c:
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, total, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, total, tag)
        _refund(c, ib, total, tag)
        base_merchant = _balance(c, mb, tag)

        mv = _new_merchant(c, tag)
        iv = _new_intent(c, mv, total, tag)
        _authorize(c, iv, tag)
        _capture(c, iv, total, tag)
        _refund(c, iv, part1, tag)
        _refund(c, iv, part2, tag)
        var_merchant = _balance(c, mv, tag)

    exp_merchant = base_merchant - CAPTURE_FEE if fee_adjusted else base_merchant
    assert var_merchant == exp_merchant, (
        f"{tag} split refund: refunding {total} as two parts left the merchant at "
        f"{var_merchant}, not {exp_merchant} (single full refund baseline "
        f"{base_merchant}, fee {CAPTURE_FEE}, fee_adjusted={fee_adjusted}); a refund "
        f"carries no capture fee, so splitting a refund must change no balance"
    )


def _check_reorder_independent(amount_a, amount_b, tag):
    with _client() as c:
        ma = _new_merchant(c, tag)
        ia = _new_intent(c, ma, amount_a, tag)
        _authorize(c, ia, tag)
        _capture(c, ia, amount_a, tag)
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, amount_b, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, amount_b, tag)
        base_a = _balance(c, ma, tag)
        base_b = _balance(c, mb, tag)

        nb = _new_merchant(c, tag)
        jb = _new_intent(c, nb, amount_b, tag)
        _authorize(c, jb, tag)
        _capture(c, jb, amount_b, tag)
        na = _new_merchant(c, tag)
        ja = _new_intent(c, na, amount_a, tag)
        _authorize(c, ja, tag)
        _capture(c, ja, amount_a, tag)
        var_a = _balance(c, na, tag)
        var_b = _balance(c, nb, tag)

    assert var_a == base_a and var_b == base_b, (
        f"{tag} reorder independent: swapping the order of operations on disjoint "
        f"merchant accounts changed a final balance (merchant A {base_a}->{var_a}, "
        f"merchant B {base_b}->{var_b}); independent operations must commute"
    )


def _check_replay_request(amount, times, tag):
    with _client() as c:
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, amount, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, amount, tag)
        base_merchant = _balance(c, mb, tag)

        mv = _new_merchant(c, tag)
        iv = _new_intent(c, mv, amount, tag)
        _authorize(c, iv, tag)
        rk = uuid.uuid4().hex
        first = _capture(c, iv, amount, tag, key=rk)
        for _ in range(times):
            again = _capture(c, iv, amount, tag, key=rk)
            assert again == first, f"{tag} replay returned a different response body than the first call"
        var_merchant = _balance(c, mv, tag)
        var_intent = _get_intent(c, iv, tag)

    assert var_merchant == base_merchant, (
        f"{tag} replay: replaying an identical capture {times} time(s) changed the "
        f"merchant balance {base_merchant}->{var_merchant}; a replay must have no new effect"
    )
    assert var_intent["captured_amount"] == amount, (
        f"{tag} replay: captured_amount is {var_intent['captured_amount']} after replay but "
        f"exactly one capture of {amount} happened; a replayed key must never double book"
    )


def _check_void_recreate(amount, tag):
    with _client() as c:
        mb = _new_merchant(c, tag)
        ib = _new_intent(c, mb, amount, tag)
        _authorize(c, ib, tag)
        _capture(c, ib, amount, tag)
        base_merchant = _balance(c, mb, tag)

        mv = _new_merchant(c, tag)
        iv = _new_intent(c, mv, amount, tag)
        _authorize(c, iv, tag)
        _void(c, iv, tag)
        iv2 = _new_intent(c, mv, amount, tag)
        _authorize(c, iv2, tag)
        _capture(c, iv2, amount, tag)
        var_merchant = _balance(c, mv, tag)

    assert var_merchant == base_merchant, (
        f"{tag} void-recreate: voiding then recreating an identical intent left the "
        f"merchant at {var_merchant}, not {base_merchant} (as if never voided); a "
        f"released hold must leave no residue"
    )


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(
    part1=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
    part2=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
)
def test_mr_split_capture_fee_adjusted(part1, part2):
    # [MR-1] split_capture, fee_adjusted=True
    _check_split_capture(part1, part2, True, "[MR-1]")


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(
    amount_a=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
    amount_b=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
)
def test_mr_reorder_independent_exact_equivalence(amount_a, amount_b):
    # [MR-2] reorder_independent (exact equivalence)
    _check_reorder_independent(amount_a, amount_b, "[MR-2]")


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(
    base_amount=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
    k=st.integers(min_value=2, max_value=5),
)
def test_mr_scale_amounts_exact_equivalence(base_amount, k):
    # [MR-3] scale_amounts, fee_adjusted=False
    _check_scale_amounts(base_amount, k, False, "[MR-3]")


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(
    amount=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
    times=st.integers(min_value=1, max_value=3),
)
def test_mr_replay_request_exact_equivalence(amount, times):
    # [MR-4] replay_request (idempotency identity)
    _check_replay_request(amount, times, "[MR-4]")


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(amount=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE))
def test_mr_void_recreate_fee_adjusted(amount):
    # [MR-5] void_recreate (exact equivalence)
    _check_void_recreate(amount, "[MR-5]")


@settings(max_examples=_MR_MAX_EXAMPLES, deadline=None, derandomize=True)
@given(
    part1=st.integers(min_value=MIN_CAPTURE, max_value=MAX_CAPTURE),
    part2=st.integers(min_value=1, max_value=MAX_CAPTURE),
)
def test_mr_split_refund_fee_adjusted(part1, part2):
    # [MR-6] split_refund, fee_adjusted=False
    _check_split_refund(part1, part2, False, "[MR-6]")
