"""Deterministic renderer: agent proposals -> a runnable Hypothesis module.

No LLM here (design section 7.1: propose vs dispose). The compiler owns the
concrete enactment of every effect and invariant kind; the agent only chose the
bindings (which operation has which effect, which states are legal, which
invariants hold). A wrong binding renders into a wrong assertion that Hypothesis
then falsifies, which is exactly the signal triage classifies.

Generated code drives the HTTP API only. The capture fee and the well known
system account IDs are harness supplied config (the fee via env, the IDs are the
stable public IDs of spec section 2.1); they are not discovered from the
OpenAPI document, and the report says so.
"""

from __future__ import annotations

from ..schemas import Invariant, Rule

_EFFECT_LEGAL_DEFAULT = {
    "authorize": ["CREATED"],
    "capture": ["AUTHORIZED", "PARTIALLY_CAPTURED"],
    "refund": ["CAPTURED", "PARTIALLY_REFUNDED"],
    "void": ["CREATED", "AUTHORIZED", "PARTIALLY_CAPTURED"],
}

# The rendered failure message is a contract: a coding agent reads "[INV-4] money
# not conserved" and acts on it, so the id has to be the FROZEN spec id
# (specs/invariants.md), not whatever the agent happened to name its proposal.
# The agent numbers its own invariants freely and has, on one run, called
# conservation "INV-3"; keyed by the closed invariant kind, this map pins the
# public label to the frozen numbering so the message never lies about which rule
# broke. tests/drift/test_spec_coverage.py asserts each oracle carries its
# canonical tag, so a renderer that stopped normalizing would fail the gate.
_CANONICAL_INV_ID = {
    "captured_le_authorized": "INV-1",
    "refunded_le_captured": "INV-2",
    "nonneg_balance": "INV-3",
    "conservation_zero": "INV-4",
}


def _states_set(states: list[str]) -> str:
    return "{" + ", ".join(repr(s) for s in states) + "}" if states else "set()"


def _header(n_rules: int, n_invariants: int) -> str:
    return f'''"""GENERATED by agent/codegen.compile_spec. Do not edit by hand.

Compiled from {n_rules} agent proposed rules and {n_invariants} invariants into a
Hypothesis RuleBasedStateMachine (design section 7.3). Drives the PayFlow HTTP
API only. Regenerate with `uv run agent-run`; this file is the committed current
accepted Layer 1 spec.

  SUT base URL: env PAYFLOW_SUT_BASE_URL
  Capture fee:  env PAYFLOW_CAPTURE_FEE (harness supplied, not from OpenAPI)
"""

from __future__ import annotations

import os
import uuid

import httpx
from hypothesis import settings
from hypothesis.stateful import Bundle, RuleBasedStateMachine, invariant, rule
from hypothesis.strategies import integers

BASE_URL = os.environ.get("PAYFLOW_SUT_BASE_URL", "http://127.0.0.1:8000")
CAPTURE_FEE = int(os.environ.get("PAYFLOW_CAPTURE_FEE", "30"))

MIN_AMOUNT = max(CAPTURE_FEE * 4, 400)
MAX_AMOUNT = 100_000


def _key() -> dict:
    return {{"Idempotency-Key": uuid.uuid4().hex}}
'''


_CLASS_PREAMBLE = '''

class PayFlowGeneratedMachine(RuleBasedStateMachine):
    accounts = Bundle("accounts")
    intents = Bundle("intents")

    def __init__(self) -> None:
        super().__init__()
        # Per-step checks read only entities this instance created (self._model,
        # self._merchants). For the once-per-example conservation check (INV-4) we
        # record a baseline of the shared system accounts here and assert MY net
        # delta against it in teardown: examples run sequentially, so between this
        # baseline and teardown only this instance's operations move those accounts,
        # which makes a true global debit==credit check safe on a shared server.
        self._client = httpx.Client(base_url=BASE_URL, timeout=30.0)
        self._model: dict[str, dict] = {}
        self._merchants: list[str] = []
        self._merchant_expected: dict[str, int] = {}
        self._system_accounts = ("acct_external_settlement", "acct_holds", "acct_platform_fees")
        self._system_baseline = {a: self._balance(a) for a in self._system_accounts}

    # teardown() is composed by the compiler (render_module): it runs the
    # once-per-example invariant checks (conservation, non-negativity), then
    # always closes the client.

    # -- shared helpers ---------------------------------------------------

    def _remote_intent(self, intent_id: str) -> dict:
        response = self._client.get(f"/payment_intents/{intent_id}")
        assert response.status_code == 200, response.text
        return response.json()

    def _balance(self, account_id: str) -> int:
        response = self._client.get(f"/accounts/{account_id}/balance")
        assert response.status_code == 200, response.text
        return response.json()["balance"]

    def _assert_unchanged(self, intent_id: str, tag: str) -> None:
        model = self._model[intent_id]
        body = self._remote_intent(intent_id)
        assert body["state"] == model["state"], f"{tag} state changed on a rejected call"
        assert body["captured_amount"] == model["captured"], f"{tag} captured changed on a rejected call"
        assert body["refunded_amount"] == model["refunded"], f"{tag} refunded changed on a rejected call"
'''


def _create_account_rule(r: Rule) -> str:
    return f'''
    @rule(target=accounts)
    def {r.name}(self):
        # [RULE {r.name}] operation {r.operation_id}
        response = self._client.post("/accounts", json={{"name": "acme"}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status}, got {{response.status_code}}: {{response.text}}"
        account_id = response.json()["id"]
        self._merchants.append(account_id)
        self._merchant_expected[account_id] = 0
        return account_id
'''


def _create_intent_rule(r: Rule) -> str:
    return f'''
    @rule(target=intents, account=accounts, amount=integers(min_value=MIN_AMOUNT, max_value=MAX_AMOUNT))
    def {r.name}(self, account, amount):
        # [RULE {r.name}] operation {r.operation_id}
        response = self._client.post("/payment_intents", json={{"merchant_account_id": account, "amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status}, got {{response.status_code}}: {{response.text}}"
        intent_id = response.json()["id"]
        self._model[intent_id] = {{"merchant": account, "amount": amount, "authorized": 0, "captured": 0, "refunded": 0, "state": "CREATED"}}
        return intent_id
'''


def _authorize_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents)
    def {r.name}(self, intent):
        # [RULE {r.name}] effect=authorize legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/authorize", headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["authorized"] = model["amount"]
        model["state"] = "AUTHORIZED"

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/authorize", headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _capture_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def {r.name}(self, intent, raw):
        # [RULE {r.name}] effect=capture legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        remaining = model["authorized"] - model["captured"]
        if remaining <= CAPTURE_FEE + 1:
            return
        amount = CAPTURE_FEE + 1 + (raw % (remaining - CAPTURE_FEE))
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["captured"] += amount
        # The fee is drawn from external settlement, not the merchant (ADR-0005),
        # so the merchant is credited the full captured amount.
        self._merchant_expected[model["merchant"]] += amount
        model["state"] = "CAPTURED" if model["captured"] == model["authorized"] else "PARTIALLY_CAPTURED"

    @rule(intent=intents)
    def {r.name}_over_limit_rejected(self, intent):
        # [RULE {r.name}_over_limit] INV-1 boundary: capture beyond the remaining hold must be rejected
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        remaining = model["authorized"] - model["captured"]
        amount = remaining + 1
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": amount}}, headers=_key())
        assert response.status_code == 422, f"[RULE {r.name}_over_limit] expected 422 capturing {{amount}} over remaining {{remaining}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_over_limit]")

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": CAPTURE_FEE + 1}}, headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _refund_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def {r.name}(self, intent, raw):
        # [RULE {r.name}] effect=refund legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        refundable = model["captured"] - model["refunded"]
        if refundable < 1:
            return
        amount = 1 + (raw % refundable)
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["refunded"] += amount
        self._merchant_expected[model["merchant"]] -= amount
        model["state"] = "REFUNDED" if model["refunded"] == model["captured"] else "PARTIALLY_REFUNDED"

    @rule(intent=intents)
    def {r.name}_over_limit_rejected(self, intent):
        # [RULE {r.name}_over_limit] INV-2 boundary: refund beyond the refundable amount must be rejected
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        refundable = model["captured"] - model["refunded"]
        amount = refundable + 1
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": amount}}, headers=_key())
        assert response.status_code == 422, f"[RULE {r.name}_over_limit] expected 422 refunding {{amount}} over refundable {{refundable}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_over_limit]")

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": 1}}, headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _void_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents)
    def {r.name}(self, intent):
        # [RULE {r.name}] effect=void legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/void", headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["state"] = "VOIDED"

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/void", headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


# Per-step invariants: checked after every rule via @invariant(). Each reads only
# this instance's own intents, so it is cheap and safe on the shared server.
_PER_STEP_INVARIANTS = {
    "captured_le_authorized": '''
    @invariant()
    def {name}(self):
        # [{id}] captured_amount <= authorized_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["captured_amount"] <= body["authorized_amount"], f"[{id}] {{intent_id}}: captured {{body['captured_amount']}} > authorized {{body['authorized_amount']}}"
''',
    "refunded_le_captured": '''
    @invariant()
    def {name}(self):
        # [{id}] refunded_amount <= captured_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["refunded_amount"] <= body["captured_amount"], f"[{id}] {{intent_id}}: refunded {{body['refunded_amount']}} > captured {{body['captured_amount']}}"
''',
}

# Per-example checks: run once from the composed teardown(), not after every step.
# They read several account balances, so a per-step @invariant would multiply HTTP
# calls by the step count (measured ~8x slower). A violation they catch (a broken
# ledger pair, an over-refund to a negative balance) persists to the end of the
# sequence, so one check per example is sufficient and keeps the suite fast.
# Rendered as plain methods that teardown() calls by name.
_PER_EXAMPLE_CHECKS = {
    "conservation_zero": '''
    def _check_{name}(self):
        # [{id}] global conservation of money: every ledger movement is a
        # balanced debit/credit pair, so the net change across ALL accounts this
        # instance touched must be exactly zero. Measured as a delta against the
        # per-instance system-account baseline plus this instance's merchant
        # balances (merchants start at zero, so their absolute balance is their
        # delta). A dropped or misweighted pair leaves the net non-zero.
        net = 0
        for account_id, baseline in self._system_baseline.items():
            net += self._balance(account_id) - baseline
        for account_id in self._merchants:
            net += self._balance(account_id)
        assert net == 0, f"[{id}] money not conserved: net delta across every account this run touched is {{net}}, must be 0 (debits == credits)"
''',
    "nonneg_balance": '''
    def _check_{name}(self):
        # [{id}] no merchant, holds, or platform_fees balance ever goes negative;
        # external_settlement is the funding source and may. Merchant checks
        # are scoped to this instance's accounts; holds and platform_fees are
        # globally non-negative by construction (holds only carries outstanding
        # authorizations, platform_fees is only ever credited), so their absolute
        # balance is safe to assert on the shared server.
        for account_id in self._merchants:
            balance = self._balance(account_id)
            assert balance >= 0, f"[{id}] merchant {{account_id}} balance is negative: {{balance}}"
        for account_id in ("acct_holds", "acct_platform_fees"):
            balance = self._balance(account_id)
            assert balance >= 0, f"[{id}] system account {{account_id}} balance is negative: {{balance}}"
''',
}

# Combined view for validation and the vocabulary drift gate (tests/drift).
_INVARIANTS = {**_PER_STEP_INVARIANTS, **_PER_EXAMPLE_CHECKS}


def _rule_block(r: Rule) -> str:
    if r.kind == "create_account":
        return _create_account_rule(r)
    if r.kind == "create_intent":
        return _create_intent_rule(r)
    if r.kind == "query" or r.effect == "none":
        return ""  # queries need no mutating rule; invariants drive the GETs
    legal = _states_set(r.legal_states or _EFFECT_LEGAL_DEFAULT.get(r.effect, []))
    if r.effect == "authorize":
        return _authorize_rules(r, legal)
    if r.effect == "capture":
        return _capture_rules(r, legal)
    if r.effect == "refund":
        return _refund_rules(r, legal)
    if r.effect == "void":
        return _void_rules(r, legal)
    return ""


def _invariant_block(inv: Invariant) -> str:
    template = _INVARIANTS.get(inv.kind)
    if template is None:
        # A closed-vocabulary member with no template would render to nothing and
        # pass vacuously, a silent hole in the Layer 1 gate. Fail loudly at
        # generation time; tests/drift/test_vocabulary_coupling keeps this map in
        # lockstep with schemas.InvariantKind so a correct build never hits this.
        raise ValueError(
            f"no render template for invariant kind {inv.kind!r}; a new InvariantKind "
            "must ship with a template in _PER_STEP_INVARIANTS or _PER_EXAMPLE_CHECKS"
        )
    # Pin the public id to the frozen spec numbering by kind (see _CANONICAL_INV_ID);
    # fall back to the agent's own id only for a kind we have not mapped.
    canonical_id = _CANONICAL_INV_ID.get(inv.kind, inv.id)
    return template.format(name=inv.name, id=canonical_id)


def _render_teardown(per_example_names: list[str]) -> str:
    """Compose teardown(): run each once-per-example check, then close the client."""
    calls = "".join(f"            self._check_{name}()\n" for name in per_example_names)
    body = calls or "            pass\n"
    return (
        "\n"
        "    def teardown(self) -> None:\n"
        "        # Run the once-per-example invariant checks (INV-4 conservation,\n"
        "        # INV-3 non-negativity), then always close the client. A failure\n"
        "        # here fails the example and shrinks like any other assertion.\n"
        "        try:\n"
        f"{body}"
        "        finally:\n"
        "            self._client.close()\n"
    )


def render_module(
    rules: list[Rule],
    invariants: list[Invariant],
    max_examples: int,
    step_count: int,
) -> str:
    """Render the full generated module source."""
    parts = [_header(len(rules), len(invariants)), _CLASS_PREAMBLE]
    for r in rules:
        parts.append(_rule_block(r))
    per_example_names: list[str] = []
    for inv in invariants:
        parts.append(_invariant_block(inv))
        if inv.kind in _PER_EXAMPLE_CHECKS:
            per_example_names.append(inv.name)
    parts.append(_render_teardown(per_example_names))
    footer = (
        f"\n\n# Budgets are env overridable so a bug hunt can widen the search"
        f" (examples cost\n# time, not tokens) while the committed replay slice"
        f" stays modest.\n"
        f"_MAX_EXAMPLES = int(os.environ.get('PAYFLOW_SPEC_MAX_EXAMPLES', '{max_examples}'))\n"
        f"_STEP_COUNT = int(os.environ.get('PAYFLOW_SPEC_STEP_COUNT', '{step_count}'))\n"
        f"PayFlowGeneratedMachine.TestCase.settings = settings(\n"
        f"    max_examples=_MAX_EXAMPLES, stateful_step_count=_STEP_COUNT, deadline=None\n"
        f")\n"
        f"TestGeneratedMachine = PayFlowGeneratedMachine.TestCase\n"
    )
    parts.append(footer)
    return "".join(parts)
