"""Deterministic renderer: agent proposals -> a runnable Hypothesis module.

No LLM here (design section 7.1: propose vs dispose). The compiler owns the
concrete enactment of every effect and invariant kind; the agent only chose the
bindings (which operation has which effect, which states are legal, which
invariants hold). A wrong binding renders into a wrong assertion that Hypothesis
then falsifies, which is exactly the signal triage classifies.

Generated code drives the HTTP API only. The capture fee and the well known
system account IDs are harness supplied config (the fee via env, the IDs are the
stable public IDs of spec section 2.1); they are not discovered from the
OpenAPI document, and the report says so.
"""

from __future__ import annotations

from ..schemas import Invariant, Rule

_EFFECT_LEGAL_DEFAULT = {
    "authorize": ["CREATED"],
    "capture": ["AUTHORIZED", "PARTIALLY_CAPTURED"],
    "refund": ["CAPTURED", "PARTIALLY_REFUNDED"],
    "void": ["CREATED", "AUTHORIZED", "PARTIALLY_CAPTURED"],
}


def _states_set(states: list[str]) -> str:
    return "{" + ", ".join(repr(s) for s in states) + "}" if states else "set()"


def _header(n_rules: int, n_invariants: int) -> str:
    return f'''"""GENERATED by agent/codegen.compile_spec. Do not edit by hand.

Compiled from {n_rules} agent proposed rules and {n_invariants} invariants into a
Hypothesis RuleBasedStateMachine (design section 7.3). Drives the PayFlow HTTP
API only. Regenerate with `uv run agent-run`; this file is the committed current
accepted Layer 1 spec.

  SUT base URL: env PAYFLOW_SUT_BASE_URL
  Capture fee:  env PAYFLOW_CAPTURE_FEE (harness supplied, not from OpenAPI)
"""

from __future__ import annotations

import os
import uuid

import httpx
from hypothesis import settings
from hypothesis.stateful import Bundle, RuleBasedStateMachine, invariant, rule
from hypothesis.strategies import integers

BASE_URL = os.environ.get("PAYFLOW_SUT_BASE_URL", "http://127.0.0.1:8000")
CAPTURE_FEE = int(os.environ.get("PAYFLOW_CAPTURE_FEE", "30"))

MIN_AMOUNT = max(CAPTURE_FEE * 4, 400)
MAX_AMOUNT = 100_000


def _key() -> dict:
    return {{"Idempotency-Key": uuid.uuid4().hex}}
'''


_CLASS_PREAMBLE = '''

class PayFlowGeneratedMachine(RuleBasedStateMachine):
    accounts = Bundle("accounts")
    intents = Bundle("intents")

    def __init__(self) -> None:
        super().__init__()
        # The SUT is a live server whose database persists across Hypothesis
        # examples, so every check below reads only entities this instance
        # created (self._model, self._merchants, self._merchant_expected).
        # Reading global state would make the same step sequence behave
        # differently across examples (Hypothesis flags that as flaky).
        self._client = httpx.Client(base_url=BASE_URL, timeout=30.0)
        self._model: dict[str, dict] = {}
        self._merchants: list[str] = []
        self._merchant_expected: dict[str, int] = {}

    def teardown(self) -> None:
        self._client.close()

    # -- shared helpers ---------------------------------------------------

    def _remote_intent(self, intent_id: str) -> dict:
        response = self._client.get(f"/payment_intents/{intent_id}")
        assert response.status_code == 200, response.text
        return response.json()

    def _balance(self, account_id: str) -> int:
        response = self._client.get(f"/accounts/{account_id}/balance")
        assert response.status_code == 200, response.text
        return response.json()["balance"]

    def _assert_unchanged(self, intent_id: str, tag: str) -> None:
        model = self._model[intent_id]
        body = self._remote_intent(intent_id)
        assert body["state"] == model["state"], f"{tag} state changed on a rejected call"
        assert body["captured_amount"] == model["captured"], f"{tag} captured changed on a rejected call"
        assert body["refunded_amount"] == model["refunded"], f"{tag} refunded changed on a rejected call"
'''


def _create_account_rule(r: Rule) -> str:
    return f'''
    @rule(target=accounts)
    def {r.name}(self):
        # [RULE {r.name}] operation {r.operation_id}
        response = self._client.post("/accounts", json={{"name": "acme"}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status}, got {{response.status_code}}: {{response.text}}"
        account_id = response.json()["id"]
        self._merchants.append(account_id)
        self._merchant_expected[account_id] = 0
        return account_id
'''


def _create_intent_rule(r: Rule) -> str:
    return f'''
    @rule(target=intents, account=accounts, amount=integers(min_value=MIN_AMOUNT, max_value=MAX_AMOUNT))
    def {r.name}(self, account, amount):
        # [RULE {r.name}] operation {r.operation_id}
        response = self._client.post("/payment_intents", json={{"merchant_account_id": account, "amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status}, got {{response.status_code}}: {{response.text}}"
        intent_id = response.json()["id"]
        self._model[intent_id] = {{"merchant": account, "amount": amount, "authorized": 0, "captured": 0, "refunded": 0, "state": "CREATED"}}
        return intent_id
'''


def _authorize_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents)
    def {r.name}(self, intent):
        # [RULE {r.name}] effect=authorize legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/authorize", headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["authorized"] = model["amount"]
        model["state"] = "AUTHORIZED"

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/authorize", headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _capture_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def {r.name}(self, intent, raw):
        # [RULE {r.name}] effect=capture legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        remaining = model["authorized"] - model["captured"]
        if remaining <= CAPTURE_FEE + 1:
            return
        amount = CAPTURE_FEE + 1 + (raw % (remaining - CAPTURE_FEE))
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["captured"] += amount
        # The fee is drawn from external settlement, not the merchant (ADR-0005),
        # so the merchant is credited the full captured amount.
        self._merchant_expected[model["merchant"]] += amount
        model["state"] = "CAPTURED" if model["captured"] == model["authorized"] else "PARTIALLY_CAPTURED"

    @rule(intent=intents)
    def {r.name}_over_limit_rejected(self, intent):
        # [RULE {r.name}_over_limit] INV-1 boundary: capture beyond the remaining hold must be rejected
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        remaining = model["authorized"] - model["captured"]
        amount = remaining + 1
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": amount}}, headers=_key())
        assert response.status_code == 422, f"[RULE {r.name}_over_limit] expected 422 capturing {{amount}} over remaining {{remaining}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_over_limit]")

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/capture", json={{"amount": CAPTURE_FEE + 1}}, headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _refund_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents, raw=integers(min_value=0, max_value=10**9))
    def {r.name}(self, intent, raw):
        # [RULE {r.name}] effect=refund legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        refundable = model["captured"] - model["refunded"]
        if refundable < 1:
            return
        amount = 1 + (raw % refundable)
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": amount}}, headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["refunded"] += amount
        self._merchant_expected[model["merchant"]] -= amount
        model["state"] = "REFUNDED" if model["refunded"] == model["captured"] else "PARTIALLY_REFUNDED"

    @rule(intent=intents)
    def {r.name}_over_limit_rejected(self, intent):
        # [RULE {r.name}_over_limit] INV-2 boundary: refund beyond the refundable amount must be rejected
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        refundable = model["captured"] - model["refunded"]
        amount = refundable + 1
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": amount}}, headers=_key())
        assert response.status_code == 422, f"[RULE {r.name}_over_limit] expected 422 refunding {{amount}} over refundable {{refundable}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_over_limit]")

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/refund", json={{"amount": 1}}, headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


def _void_rules(r: Rule, legal: str) -> str:
    return f'''
    @rule(intent=intents)
    def {r.name}(self, intent):
        # [RULE {r.name}] effect=void legal_states={r.legal_states}
        model = self._model[intent]
        if model["state"] not in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/void", headers=_key())
        assert response.status_code == {r.success_status}, f"[RULE {r.name}] expected {r.success_status} in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        model["state"] = "VOIDED"

    @rule(intent=intents)
    def {r.name}_illegal_state_rejected(self, intent):
        # [RULE {r.name}_illegal_state] precondition enforcement (INV-6)
        model = self._model[intent]
        if model["state"] in {legal}:
            return
        response = self._client.post(f"/payment_intents/{{intent}}/void", headers=_key())
        assert response.status_code == 409, f"[RULE {r.name}_illegal_state] expected 409 in state {{model['state']}}, got {{response.status_code}}: {{response.text}}"
        self._assert_unchanged(intent, "[RULE {r.name}_illegal_state]")
'''


_INVARIANTS = {
    "captured_le_authorized": '''
    @invariant()
    def {name}(self):
        # [{id}] captured_amount <= authorized_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["captured_amount"] <= body["authorized_amount"], f"[{id}] {{intent_id}}: captured {{body['captured_amount']}} > authorized {{body['authorized_amount']}}"
''',
    "refunded_le_captured": '''
    @invariant()
    def {name}(self):
        # [{id}] refunded_amount <= captured_amount
        for intent_id in self._model:
            body = self._remote_intent(intent_id)
            assert body["refunded_amount"] <= body["captured_amount"], f"[{id}] {{intent_id}}: refunded {{body['refunded_amount']}} > captured {{body['captured_amount']}}"
''',
    "conservation_zero": '''
    @invariant()
    def {name}(self):
        # [{id}] conservation of money, as a per merchant balance agreement: each
        # merchant's server balance must equal captures minus refunds. The fee is
        # drawn from external settlement, not the merchant (ADR-0005), so it does
        # not enter the merchant balance. The API exposes no ledger listing, so a
        # global debit==credit sum is not reachable over HTTP without reading state
        # from other examples; this instance local check is the strongest
        # conservation proxy available.
        for merchant, expected in self._merchant_expected.items():
            actual = self._balance(merchant)
            assert actual == expected, f"[{id}] merchant {{merchant}} balance {{actual}} != expected {{expected}} (captures - refunds)"
''',
    "nonneg_balance": '''
    @invariant()
    def {name}(self):
        # [{id}] merchant balances never go negative. Scoped to this instance's
        # merchants only: the shared system accounts (holds, platform_fees) are
        # global to the live server, so reading them would leak state from other
        # Hypothesis examples and make shrinking flaky.
        for account_id in self._merchants:
            balance = self._balance(account_id)
            assert balance >= 0, f"[{id}] merchant {{account_id}} balance is negative: {{balance}}"
''',
}


def _rule_block(r: Rule) -> str:
    if r.kind == "create_account":
        return _create_account_rule(r)
    if r.kind == "create_intent":
        return _create_intent_rule(r)
    if r.kind == "query" or r.effect == "none":
        return ""  # queries need no mutating rule; invariants drive the GETs
    legal = _states_set(r.legal_states or _EFFECT_LEGAL_DEFAULT.get(r.effect, []))
    if r.effect == "authorize":
        return _authorize_rules(r, legal)
    if r.effect == "capture":
        return _capture_rules(r, legal)
    if r.effect == "refund":
        return _refund_rules(r, legal)
    if r.effect == "void":
        return _void_rules(r, legal)
    return ""


def _invariant_block(inv: Invariant) -> str:
    template = _INVARIANTS.get(inv.kind)
    if template is None:
        return ""
    return template.format(name=inv.name, id=inv.id)


def render_module(
    rules: list[Rule],
    invariants: list[Invariant],
    max_examples: int,
    step_count: int,
) -> str:
    """Render the full generated module source."""
    parts = [_header(len(rules), len(invariants)), _CLASS_PREAMBLE]
    for r in rules:
        parts.append(_rule_block(r))
    for inv in invariants:
        parts.append(_invariant_block(inv))
    footer = (
        f"\n\n# Budgets are env overridable so a bug hunt can widen the search"
        f" (examples cost\n# time, not tokens) while the committed replay slice"
        f" stays modest.\n"
        f"_MAX_EXAMPLES = int(os.environ.get('PAYFLOW_SPEC_MAX_EXAMPLES', '{max_examples}'))\n"
        f"_STEP_COUNT = int(os.environ.get('PAYFLOW_SPEC_STEP_COUNT', '{step_count}'))\n"
        f"PayFlowGeneratedMachine.TestCase.settings = settings(\n"
        f"    max_examples=_MAX_EXAMPLES, stateful_step_count=_STEP_COUNT, deadline=None\n"
        f")\n"
        f"TestGeneratedMachine = PayFlowGeneratedMachine.TestCase\n"
    )
    parts.append(footer)
    return "".join(parts)
